import dotenv from 'dotenv';
dotenv.config();

export const envHandler = {
    PAY_IN_API_KEY: process.env.PAY_IN_API_KEY,
    PAY_IN_SALT: process.env.PAY_IN_SALT,
    PAY_OUT_API_KEY: process.env.PAY_OUT_API_KEY,
    PAY_OUT_SALT: process.env.PAY_OUT_SALT,

    // Fund transfer
    FUND_TRANSFER_URL: process.env.FUND_TRANSFER_URL,
    FUND_TRANSFER_STATUS_URL: process.env.FUND_TRANSFER_STATUS_URL,
    FUND_TRANSFER_GET_BALANCE_URL:process.env.FUND_TRANSFER_GET_BALANCE_URL,
    FUND_TRANSFER_WHITELISTING_URL:process.env.FUND_TRANSFER_WHITELISTING_URL,
    FUND_TRANSFER_WHITELISTING_TEAM_URL:process.env.FUND_TRANSFER_WHITELISTING_TEAM_URL,
    FUND_TRANSFER_GET_STATEMENT_URL:process.env.FUND_TRANSFER_GET_STATEMENT_URL,

    // Pay-in
    PAYMENT_REQUEST_URL:process.env.PAYMENT_REQUEST_URL,
    PAYMENT_REQUESTURL_URL:process.env.PAYMENT_REQUESTURL_URL,
    EXPIRE_PAYMENT_REQUEST_URL:process.env.EXPIRE_PAYMENT_REQUEST_URL,
    PAYMENT_REQUEST_INTENT_URL:process.env.PAYMENT_REQUEST_INTENT_URL,
}