import dotenv from 'dotenv';
dotenv.config();

export const envHandler = {
    PAY_IN_API_KEY: process.env.PAY_IN_API_KEY,
    PAY_IN_SALT: process.env.PAY_IN_SALT,
    PAY_OUT_API_KEY: process.env.PAY_OUT_API_KEY,
    PAY_OUT_SALT: process.env.PAY_OUT_SALT,

    // Fund transfer
    FUND_TRANSFER_URL: process.env.FUND_TRANSFER_URL,
    FUND_TRANSFER_STATUS_URL: process.env.FUND_TRANSFER_STATUS_URL,
    FUND_TRANSFER_GET_BALANCE_URL: process.env.FUND_TRANSFER_GET_BALANCE_URL,
    FUND_TRANSFER_WHITELISTING_URL: process.env.FUND_TRANSFER_WHITELISTING_URL,
    FUND_TRANSFER_WHITELISTING_TEAM_URL: process.env.FUND_TRANSFER_WHITELISTING_TEAM_URL,
    FUND_TRANSFER_GET_STATEMENT_URL: process.env.FUND_TRANSFER_GET_STATEMENT_URL,

    // Pay-in
    PAYMENT_REQUEST_URL: process.env.PAYMENT_REQUEST_URL,
    PAYMENT_REQUESTURL_URL: process.env.PAYMENT_REQUESTURL_URL,
    EXPIRE_PAYMENT_REQUEST_URL: process.env.EXPIRE_PAYMENT_REQUEST_URL,
    PAYMENT_REQUEST_INTENT_URL: process.env.PAYMENT_REQUEST_INTENT_URL,
    
    PAYMENT_STATUS_URL: process.env.PAYMENT_STATUS_URL,
    REFUND_URL: process.env.REFUND_URL,
    REFUND_STATUS_URL: process.env.REFUND_STATUS_URL,
    SPLIT_SETTLEMENT_REQ_URL:process.env.SPLIT_SETTLEMENT_REQ_URL,
    ADD_VENDOR_URL: process.env.ADD_VENDOR_URL,
    MODIFY_VENDOR_URL: process.env.MODIFY_VENDOR_URL,
    ADD_VENDOR_ACCOUNT:process.env.ADD_VENDOR_ACCOUNT,
    DELETE_VENDOR:process.env.DELETE_VENDOR,
    VENDOR_STATUS:process.env.VENDOR_STATUS,
    GET_SETTLEMENTS:process.env.GET_SETTLEMENTS,
    GET_SETTLEMENTS_DETAIL:process.env.GET_SETTLEMENTS_DETAIL,
    REQ_CHALLAN:process.env.REQ_CHALLAN,
    REQ_CHALLAN_URL:process.env.REQ_CHALLAN_URL,
    SEAMLESS_PAYMENT_REQUEST:process.env.SEAMLESS_PAYMENT_REQUEST
}